config/routes.rb
Lend2friend::Application.routes.draw do
  resources :user_details

  devise_for :users

  root :to => "home#index"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/user_detail.rb
class UserDetail < ActiveRecord::Base
  attr_accessible :address_list_id, :alt_email, :dob, :first_name, :last_name, :middle_name, :phone_list_id, :social, :user_id

belongs_to => :user


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/user_details_controller.rb
class UserDetailsController < ApplicationController
  # GET /user_details
  # GET /user_details.json
  def index
    @user_details = UserDetail.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @user_details }
    end
  end

  # GET /user_details/1
  # GET /user_details/1.json
  def show
    @user_detail = UserDetail.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user_detail }
    end
  end

  # GET /user_details/new
  # GET /user_details/new.json
  def new
    @user_detail = UserDetail.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user_detail }
    end
  end

  # GET /user_details/1/edit
  def edit
    @user_detail = UserDetail.find(params[:id])
  end

  # POST /user_details
  # POST /user_details.json
  def create
    @user_detail = UserDetail.new(params[:user_detail])

    respond_to do |format|
      if @user_detail.save
        format.html { redirect_to @user_detail, notice: 'User detail was successfully created.' }
        format.json { render json: @user_detail, status: :created, location: @user_detail }
      else
        format.html { render action: "new" }
        format.json { render json: @user_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /user_details/1
  # PUT /user_details/1.json
  def update
    @user_detail = UserDetail.find(params[:id])

    respond_to do |format|
      if @user_detail.update_attributes(params[:user_detail])
        format.html { redirect_to @user_detail, notice: 'User detail was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_details/1
  # DELETE /user_details/1.json
  def destroy
    @user_detail = UserDetail.find(params[:id])
    @user_detail.destroy

    respond_to do |format|
      format.html { redirect_to user_details_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/user_details_helper.rb
module UserDetailsHelper
end

app/views/home/index.html.haml
%h3 Home

app/views/layouts/_navigation.html.haml
= link_to "Lend2friend", root_path, :class => 'brand'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : "Lend2friend"
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)
  %body
    %header.navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              - flash.each do |name, msg|
                %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
                  %a.close{"data-dismiss" => "alert"} ×
                  = msg
              = yield
          %footer

app/views/user_details/_form.html.haml
= form_for @user_detail do |f|
  -if @user_detail.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user_detail.errors.count, "error")} prohibited this user_detail from being saved:"
      %ul
        - @user_detail.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.hidden_field :user_id
  .field
    = f.hidden_field :address_list_id
  .field
    = f.hidden_field :phone_list_id
  .field
    = f.label :first_name, 'First Name'
    = f.text_field :first_name
  .field
    = f.label :middle_name, 'Middle Name'
    = f.text_field :middle_name
  .field
    = f.label :last_name, 'Last Name'
    = f.text_field :last_name
  .field
    = f.label :alt_email, 'Alternate E-Mail Address'
    = f.email_field :alt_email, :placeholder => 'me@example.com'
  .field
    = f.label :social, 'Social Security Number'
    Format: 555-55-5555
    = f.text_field :social
  .field
    = f.label :dob, 'Birthday'
    = f.date_select :dob
  .actions
    = f.submit 'Save', :class => 'btn'
    = button_tag 'Clear Form', :type => 'reset', :class => 'btn'

app/views/user_details/edit.html.haml
%h1 Editing user_detail

= render 'form'

= link_to 'Show', @user_detail
\|
= link_to 'Back', user_details_path

app/views/user_details/index.html.haml
%h1 Listing user_details

%table
  %tr
    %th User
    %th Address list id
    %th Phone list
    %th First name
    %th Middle name
    %th Last name
    %th Alt email
    %th Social
    %th Dob
    %th
    %th
    %th

  - @user_details.each do |user_detail|
    %tr
      %td= user_detail.user_id
      %td= user_detail.address_list_id
      %td= user_detail.phone_list_id
      %td= user_detail.first_name
      %td= user_detail.middle_name
      %td= user_detail.last_name
      %td= user_detail.alt_email
      %td= user_detail.social
      %td= user_detail.dob
      %td= link_to 'Show', user_detail
      %td= link_to 'Edit', edit_user_detail_path(user_detail)
      %td= link_to 'Destroy', user_detail, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New User detail', new_user_detail_path

app/views/user_details/new.html.haml
%h1 New User Details

= render 'form'

= link_to 'Back', user_details_path 

app/views/user_details/show.html.haml
%p#notice= notice

%p
  %b User:
  = @user_detail.user_id
%p
  %b Address list it:
  = @user_detail.address_list_id
%p
  %b Phone list:
  = @user_detail.phone_list_id
%p
  %b First name:
  = @user_detail.first_name
%p
  %b Middle name:
  = @user_detail.middle_name
%p
  %b Last name:
  = @user_detail.last_name
%p
  %b Alt email:
  = @user_detail.alt_email
%p
  %b Social:
  = @user_detail.social
%p
  %b Dob:
  = @user_detail.dob

= link_to 'Edit', edit_user_detail_path(@user_detail)
\|
= link_to 'Back', user_details_path